### ISSUE TITLE
Supporting module-based mvc project structures

### ISSUE THREAD

**Issue by Oatelaus** [oas-tools/oas-tools#108]
Similar to https://github.com/isa-group/oas-tools/issues/65

I'm looking to create a project which will use the following format:

```
root/
 auth/
  auth-controller.ts
  auth-model.ts
 other-module/
  other-module-controller.ts
  other-module-model.ts
```

To achieve this desired effect, I will need to split out the controllers into respective folders.

Is this currently supported by the project?

If not, is this something you guys would take as a PR?

**Comment by Fedelaus** [comment]
@raffrearaUS 

I've made this myself but it appears you guys weren't interested in taking that code at the time; is this something you'd be open to accepting a pull request for?

**Comment by stukker01** [comment]
I would welcome a PR solving this. Until that, there is a workaround for achieving this. Because of the way OAS router is implemented, you can set `controllers` to `parentFolder` in OAS configuration, and then use `x-router-controller: subFolder/controllerFileName` in your endpoint definitions.

**Comment by raffrearaUS** [comment]
@Fedelaus We would really appreciate any pull request. Sorry for the time it's taking us to solve all the issues, we are really busy with other projects and can't spend enough time on this one.

**Comment by caarmen** [comment]
> I would welcome a PR solving this. Until that, there is a workaround for achieving this. Because of the way OAS router is implemented, you can set `controllers` to `parentFolder` in OAS configuration, and then use `x-router-controller: subFolder/controllerFileName` in your endpoint definitions.

Hello from 5 years in the future 😅 

Did this workaround actually work? It's not working for me it seems. 

In `native/oas-router.js`, we have:

```javascript
              const opControllerName = methodObj['x-router-controller'] ?? controllerName;
              const path = commons.filePath(config.controllers, opControllerName);
```

This would do `commons.filePath("parentFolder", "subFolder/controllerFileName")`.

Then we have the `filePath` function:
```javascript
/** Returns the complete path of a file including extension.
 * @param {String} path - Path of the file
 * @param {String} name - Name of the file
 */
export function filePath(path, name) {
  const matches = fs.readdirSync(path).filter((file) => file.includes(name));
  if(matches.length > 0) {
    return `${path}/${matches[0]}`;
  }
}
```

This would do `fs.readdirSync("parentFolder").filter((file) => file.includes("subFolder/controllerFileName")`

I don't think this would work, as `subFolder/controllerFileName` isn't a **file** inside `parentFolder`.

Also note that [fs.readdirSync](https://nodejs.org/api/fs.html#fsreaddirsyncpath-options) doesn't do a recursive traversal by default.

Did I miss something?

**Comment by adambordas** [comment]
@caarmen Hey, it's been a while I've been here. 😄 Yes, what you described looks right, my workaround probably doesn't work anymore. However don't forget, it was 5 years ago, and the latest version of `oas-tools` was [2.1.7](https://github.com/oas-tools/oas-tools/tree/2.1.7) at the time. The related code [looked way different](https://github.com/oas-tools/oas-tools/blob/2.1.7/src/middleware/oas-router.js#L244) making the mentioned workaround possible.
