### ISSUE TITLE
schema not work with content text/plain

### ISSUE THREAD

**Issue by DiV666** [oas-tools/oas-tools#112]
Hello,

I am defining a response as text/plain and it throws this error:
```
TypeError: Cannot read property 'schema' of undefined at checkResponse (/opt/scaffolding/node_modules/oas-tools/src/middleware/oas-router.js:120:73)
```

definition.yaml
```
...
    responses:
      "200":
        description: Current system status description
        content:
          text/plain:
            schema:
              type: string
...
```

Is there another way to define it?

**Comment by DiV666** [comment]
I forgot to say that this error happens when I run the tests with jest:
```
describe('Health resource tests', () => {
    test('Check health endpoint', done => {
        return request(api)
            .get('v1/health')
            .end(function (err, res) {
                expect(res.statusCode).toBe(200);
                expect(res.text).toBe("ok");
                done();
            });
    });
});
```

**Comment by alessioerosferri** [comment]
@DiV666 
I have worked around this just by making sure that supertest specifies the Accept header. oas-tools seems to be defaulting to application/json if no Accept header is defined.
```
describe("And the body is empty", () => {
    test("a 400 HTTP status code is sent back", async () => {
      const res = await request(app)
        .post('/v1/screenshots')
        .set({'Accept': 'text/plain'})
        .send({
          date: "",
          time: "",
          image: "",
          campaign: "",
          format: "",
          panel_id: "",
          unit_id: ""
        })
    });
  });
```
Above works if content type in response is set to "text/plain".

I was very curious at why this was working when the app was running but not during the unit tests. Postman and pretty much all the browsers by default add the accept header to be "*/*". Supertest doesn't and this is why it happened.
I hope this helps as it did with me ;)

**Comment by DiV666** [comment]
@alessioerosferri Thankyou so much
The thing is, I also had the same problem with the livenessProbe and readinessProbe methods of kubernetes

I've been able to fix it with your suggestion, adding the Accept header in both methods:
```
httpGet:
  httpHeaders:
  - name: Accept
    value: text/plain
  path: /api/v1/health
  port: 80
  scheme: HTTP
```

**Comment by alessioerosferri** [comment]
@DiV666 Glad this has helped you. I will check out on my end how we have set up the liveness and readiness in K8s. On top of my head I recall I didn't have this issue because the health endpoint wasn't mapped in the OpenAPI doc but created in parallel in the main index file like below:
```
var spec = fs.readFileSync(path.join(__dirname, '/api/oas-doc.yaml'), 'utf8');
var oasDoc = jsyaml.safeLoad(spec);
var options_object = {
    controllers: path.join(__dirname, './controllers'),
    // logLevel: 'warning',
    customLogger: logger,
    strict: false,
    router: true,
    validator: true,
    docs: {swaggerUi: false}
};

oasTools.configure(options_object);

oasTools.initialize(oasDoc, app, function () {
    http.createServer(app).listen(serverPort, function () {
        logger.info({
            customLog: "true",
            message: `Server is running`,
            action: "Startup",
            source: "index"
        });
    });
});

app.get('/healthz', function (req, res) {
    if (isReady()) {
        res.send({
            info: "This API is running",
            name: "my-test-api"
        });
    } else {
        res.status(404).send("");
    }
});

```

**Comment by acotty** [comment]
Have a look at issue #273 to see if this the same issue as issue 273 gives the same error. Issue 273 has a PR that may fix this if it is the same issue.
