### ISSUE TITLE
Feature request: Add response validation

### ISSUE THREAD

**Issue by robaca** [oas-tools/oas-tools#119]
For development, it's very helpful to also have response validation to make sure the schema is up-to-date with the implementation code. Please add an option to perform response validation like existing on swagger-tools.

**Comment by robaca** [comment]
I just found, that response validation is part of the router logic. So for getting that validation using the router is mandatory. Is there any reason to tie the response validation to the routing? It would be great to have it even when using some different routing mechanism

**Comment by wontheone1** [comment]
Greetings! 
@robaca @raffrearaUS 

Is there a way to turn off the response validation? I think I don't want this feature and I assume there will be also performance overhead.

**Comment by wontheone1** [comment]
Some cases, if you are merely relaying external server's responses, then you can't guarantee the response schemas anyways (I am in that situation).

**Comment by alesancor1** [comment]
Since v3.0.0, the response validation has been taken out from the router logic and can now be disabled separatedly. Check out the [documentation](https://oas-tools.github.io/docs/fundamentals/config).
