### ISSUE TITLE
pre and post controller intercept

### ISSUE THREAD

**Issue by pg2203** [oas-tools/oas-tools#121]
is it possible to intercept the request before and after controller, i need to update the request with new parameter before it reaches to controller like req.ctx and also start/end recording time

**Comment by acotty** [comment]
I have the before controller intercept working if I revert https://github.com/isa-group/oas-tools/pull/223. 

Suggest looking at https://github.com/acotty/swagger-service-skeleton and search for "beforeController". Be aware at this point in time this repo is a WIP as I am converting the repo and other associated repos to upgrade from swagger 2.0 to OpenAPI 3.00 and am finding a bunch of issues.

**Comment by alesancor1** [comment]
The new v3.0.0 supports response interception as explained in [the docs](https://oas-tools.github.io/docs/customization/external-modules#special-case-interceptors).

Besides, whe've opened up a discussion in our GitHub page where you can ask questions and write posts to interact with the community. Check our [discussion board](https://github.com/orgs/oas-tools/discussions).
