### ISSUE TITLE
multipart file validation does not support `multer.fields()` configuration

### ISSUE THREAD

**Issue by robaca** [oas-tools/oas-tools#122]
When using `multer.fields([{ name: 'someFiles' }])` with express, the files can be found in the request below `req.files.someFiles` instead of `req.files`. oas-tools currently then ignores the files completely during validation.

**Comment by alesancor1** [comment]
Since the release [v3.0.0](https://oas-tools.github.io), the files are validated and can be found in `res.locals.oas.files`.
