### ISSUE TITLE
customLogger doesn't appear to work

### ISSUE THREAD

**Issue by tswaters** [oas-tools/oas-tools#144]
We're providing a custom logger in initialization options -- this is a contrived example, but highlights the problem --

```js

const options_object = {
	controllers: path.join(__dirname, '../controllers'),
	customLogger: {
		debug: (...args) => console.log('DEBUG', ...args),
		info: (...args) => console.log('INFO', ...args),
		error: (...args) => console.log('ERROR', ...args)
	},
	loglevel: 'info',
	strict: false,
	router: true,
	validator: true,
	docs: true,
	ignoreUnknownFormats: true,
}
oasTools.configure(options_object)
```

Those log functions are never called.  I think the problem is that whenever the logger is pulled out, e.g. in `oas-auth.js` something like the following appears:

```js
var config = require('../configurations'),
    logger = config.logger;
```

This happens during module initialization -- the logger here is bound early to the one that is defined in the configurations.js file.  Even though it may be updated later, it's still pointing at the original winston object that was created.

I think this needs to change to DI injection, or maybe a routine inside configuration that returns the up-to-date logger is called to get the logger....  e.g.:

```diff
+const config = require('../configurations')
-var config = require('../configurations'),
-    logger = config.logger;
```

and

```diff
 module.exports = (oasDoc) => {
  return function OASAuth (req, res, next) {
+    const logger = config.logger
 
```

**Comment by alesancor1** [comment]
The new version v3.0.0 fixes this problem. Check the documentation on [how to add a custom logger](https://oas-tools.github.io/docs/customization/custom-loger).
