### ISSUE TITLE
Do not log binary debug data to console

### ISSUE THREAD

**Issue by karoliskap** [oas-tools/oas-tools#158]
When I send Buffer data using express send function I get all the binary data printed to console, which is not very useful and makes debug log level unusable in this case.

in oas-router.js
```
function checkResponse(req, res, oldSend, oasDoc, method, requestedSpecPath, content) {
...
logger.debug("  -data: " + JSON.stringify(data));
...
```

**Comment by karoliskap** [comment]
I would also suggest printing complete specification to console optional in debug log level. It is really not very useful when debugging and requires tedious scrolling each time see some errror that is above.

**Comment by alesancor1** [comment]
The logger has been refactored and now it can be replaced by an external logger. You can check the logger configuration at the [documentation page](https://oas-tools.github.io/docs/fundamentals/config).
