### ISSUE TITLE
Set name property on validation error when using customErrorHandling: true

### ISSUE THREAD

**Issue by NikolaiGulatz** [oas-tools/oas-tools#159]
Using `customErrorHandling: true` feels really weird since you have to check on the `failedValidation` property of each error object instead of just using its name:

```javascript
function handleErrors(err, req, res, next) {
  // special case for oas-tools custom error handling
  if (err.failedValidation) {
    // do validation error stuff
  } else {
    switch(err.name) {
      case 'UnauthorizedError':
        // do stuff
        break;
      case 'SomeOtherError':
        // do other stuff
        break;
      ...
    }
  }
}
```

It would be great to just give the error a name property like "ValidationError" - this will also produce easier to understand stack traces.

**Comment by alesancor1** [comment]
The custom error handling feature has changed since the release of the new v3.0.0. Read more about it in the [documentation](https://oas-tools.github.io/docs/features/error-handling).
