### ISSUE TITLE
Does not support Server Templating

### ISSUE THREAD

**Issue by NikolaiGulatz** [oas-tools/oas-tools#160]
The OpenAPI 3 definition allows for template variables in server definitions as described [https://swagger.io/docs/specification/api-host-and-base-path/](here).

The following example does not work with `oas-tools` version `2.1.6`:

```api.yml
# api.yml
---
openapi: 3.0.0
info:
  title: TeapodAPI
  version: 0.1.0
servers:
- url: http://localhost:8080/api/{version}
  description: Development server
  variables:
    version:
      default: v1
      enum:
      - v1
paths:
  /teapod:
    get:
      x-router-controller: teapodController
      operationId: getTeapod
      responses:
        418:
          description: I'm a teapot
```

```javascript
// index.js
var oasTools = require('oas-tools');
var path = require('path');
var http = require('http');
var express = require('express');

var jsyaml = require('js-yaml');
var fs = require('fs');

var spec = fs.readFileSync(path.join('api.yml'), 'utf8');
var oasDoc = jsyaml.safeLoad(spec);

var app = express();

oasTools.initialize(oasDoc, app, function() {
  http.createServer(app).listen(8080, function() {
    console.log("App up and running!");
  });
});
```

When running the server and requesting the URL I get the generic 404 with no error output on the server console.

```shell
$ curl localhost:8080/api/v1/teapod
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v1/teapod</pre>
</body>
</html>
```

while it works when hardcoding the version number like so:

```yaml
# api_fixed.yml
---
openapi: 3.0.0
info:
  title: TeapodAPI
  version: 0.1.0
servers:
- url: http://localhost:8080/api/v1
  description: Development server
paths:
  /teapod:
    get:
      x-router-controller: teapodController
      operationId: getTeapod
      responses:
        418:
          description: I'm a teapot
```

**Comment by alesancor1** [comment]
A new release that solves this issue has been published (`v3.0.2`). Please run `npm update @oas-tools/core` to update OAS Tools core library. See the [Release Notes](https://github.com/oas-tools/oas-tools/pull/348).

**Comment by iofirag** [comment]
still not works after update to v3.0.2
the behavior still the same as wrote in the description of the issue

**Comment by alesancor1** [comment]
@iofirag I couldn't reproduce the error. The servers property works well for me with the new version, and server templating is supported, too. The spec I used to try to reproduce your problem is in [this issues' conversation](https://github.com/oas-tools/oas-tools/issues/341#issuecomment-1261323288).

**Comment by iofirag** [comment]
thanks, as we talk - it's fixed.
