### ISSUE TITLE
Support 'default' keyword for request body

### ISSUE THREAD

**Issue by NilsPe** [oas-tools/oas-tools#177]
Hello,

a schema object featuring the 'default' keyword is not processed properly. 

When sending an incomplete object in the request body, i.e. with a missing value that has a default keyword defined, the object is routed to my service as is.
Instead I expect the validator to replace missing values in the object with their default keyword.

The OpenAPI-Spec reads for this:
> default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.
>

**Comment by alesancor1** [comment]
A new release that solves this issue has been published (`v3.0.2`). Please run `npm update @oas-tools/core` to update OAS Tools core library.
