### ISSUE TITLE
Query parameter array types are not parsed properly, returning a warning.

### ISSUE THREAD

**Issue by tswaters** [oas-tools/oas-tools#178]
If you have a swagger document that has, among other things, the following:
```yaml
/test:
  get:
    parameters:
      - name: testing
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
```

And attempt to curl it using something like the following:

```
curl localhost:3000/test?testing%5B0%5D=123&testing%5B1%5D=234

( unescaped, that's testing[0]=123&testing[1]=234 )
```

You'll see a warning logged, 
```
[
    {
        "message": "wrong parameter test in query",
        "error": [
            {
                "code": "INVALID_TYPE",
                "params": [
                    "array",
                    "string"
                ],
                "message": "Expected type array but found type string"
            }
        ]
    }
]
```

This happens here:

https://github.com/isa-group/oas-tools/blob/2.1.7/src/middleware/oas-validator.js#L169-L177

When the code enters this point, it attempts to `JSON.parse(req.query.testing)`.  

`req.params.testing` at this point is already an array -- attempting to call JSON.parse with an array fails so so it goes into the catch block, and at that that point it calls `String` on it, winding up with  "123,234", which fails validation because it's a string, not an array.

It might make sense to call into `Array.isArray()` here and if the provided value is an array, don't attempt to call JSON.parse it. 

I'm not sure how many people are passing complicated data structures through querystrings -- I guess one could include JSON documents there (I for one would not)... given this possible use case, it might make sense to still parse for non-strings and non-arrays & to iterate the array (if it is one), and call `JSON.parse(item)` with a fallback to `String(item)` as well.

**Comment by ElPingos** [comment]
Hello,

Same problem here.
`/users/{ids}:
    get:
      x-swagger-router-controller: users
      operationId: get
      parameters:
        - name: ids
          in: path
          description: ids
          required: true
          schema:
            type: array
            items:
              type: integer`

And this error in the logs :

> 2019-11-26T09:21:20.609Z debug: Register: GET - /users/:ids
2019-11-26T09:21:20.610Z debug:   GET - /users/{ids}
2019-11-26T09:21:20.610Z debug:     OAS-doc has x-swagger-router-controller property users
2019-11-26T09:21:20.628Z debug:       Controller for GET - /users/{ids}: OK
2019-11-26T09:21:56.632Z debug: Checking security...
2019-11-26T09:21:56.633Z info: Requested method-url pair: get - /users/12,13,14
2019-11-26T09:21:56.634Z debug: OASValidator  -res.locals.requestedSpecPath: /users/{ids}
2019-11-26T09:21:56.637Z error: [{"message":"Wrong parameter ids in params. ","error":[{"code":"INVALID_TYPE","params":["array","string"],"message":"Expected type array but found type string","path":"#/"}]}]

Can I do anything to help fix this problem ?

**Comment by dt-atkinson** [comment]
Same issue, it works if you supply something like `localhost:/endpoint/[1,2,3]` rather than `localhost:/endpoint/1,2,3`. This I believe is erroneous.

https://swagger.io/docs/specification/serialization/

**Comment by alesancor1** [comment]
[Parameter serialization](https://swagger.io/docs/specification/serialization/) is now supported in version [v3.0.0](https://oas-tools.github.io).
