### ISSUE TITLE
Support ES6 modules

### ISSUE THREAD

**Issue by hadiosbourne** [oas-tools/oas-tools#179]
Is there any plans to support ES6 modules which is becoming stable in October 2019?
Currently the library breaks when the --experimental-modules are used, 
One instance is where the controller gets called dynamically https://github.com/isa-group/oas-tools/blob/master/src/middleware/oas-router.js#L187
I'm sure there are more cases of this

**Comment by wontheone1** [comment]
Hi I have the same request. Any plan we can use it with ES6 module soon?

**Comment by alesancor1** [comment]
Hi,

[OAS Tools 2.2.0](https://github.com/oas-tools/oas-tools/releases/tag/2.2.0) added suuport to ESM from Node 12.X. Check #271
