### ISSUE TITLE
Please consider moving snyk to devDepdendencies

### ISSUE THREAD

**Issue by tswaters** [oas-tools/oas-tools#182]
Was just tracking down a few things reported by `npm audit` and I traced it back to the `snyk` module (irony).

As far as I can tell, this should be a devDepdendency of this module... it is only references in one of the npm scripts.

Because it's marked as a dependency of this module, we wind up bringing a ton of not particularly useful things into everyone's `node_modules` directory:

```
        "snyk-config": "^2.2.1",
        "snyk-docker-plugin": "1.29.1",
        "snyk-go-plugin": "1.11.0",
        "snyk-gradle-plugin": "^3.0.2",
        "snyk-module": "1.9.1",
        "snyk-mvn-plugin": "2.4.0",
        "snyk-nodejs-lockfile-parser": "1.16.0",
        "snyk-nuget-plugin": "1.12.1",
        "snyk-php-plugin": "1.6.4",
        "snyk-policy": "1.13.5",
        "snyk-python-plugin": "^1.13.2",
        "snyk-resolve": "1.0.1",
        "snyk-resolve-deps": "4.4.0",
        "snyk-sbt-plugin": "2.8.0",
        "snyk-tree": "^1.0.0",
        "snyk-try-require": "1.3.1",
```

^^ that's a sample from my package-lock from a project using this module.  The audit is flagging `lodash < 4.17.5` in `@sync/dep-graph`

**Comment by olegjs** [comment]
Moving `snyk` to dev deps would make `oas-tools` package 5 Meg lighter 😂

**Comment by tswaters** [comment]
Turns out this is how snyk works.  See https://github.com/snyk/snyk/issues/146

**Comment by raffrearaUS** [comment]
Should I close this issue or leave it open in case snyk is not required as a production dependency in the future?

**Comment by mikeprimm-triva** [comment]
As this is a library, the notion that the 'snyk protect' run is going to be used in production, independent of how terrible an idea it is to have code patched outside of the CI/CD pipeline process is, the desire for it to be a 'dependency' vs a 'devDependency' should be a function of the top level deployed component (that is, unless my app, which uses oas-tools, happens to want to use this (somewhat dubious) pattern, the desire and mechanisms by which that would be used would be a function of my code deployment, and not a library component within my app).  The top level app is free to add 'snky' as a dependency, but there is no good way to REMOVE a dependency of a library that isn't actually needed or used by the library itself during production.
Just my $0.02.
