### ISSUE TITLE
"customErrorHandling: true" not working on response validation error

### ISSUE THREAD

**Issue by yitzgold** [oas-tools/oas-tools#184]
when I set "customErrorHandling: true" in the config options it only calls next() (to go into my custom error handling) when there is a request validation error, but for a response validation error it's not working

**Comment by arecaps** [comment]
+1

**Comment by belyaev-vladimir** [comment]
+1

**Comment by belyaev-vladimir** [comment]
I set options property strict: true and customErrorHandler: true. If the server answered incorrectly, I expect call 'next()' for handle custom errors. But this isn't happening

**Comment by alesancor1** [comment]
This behaviour was caused by the response validation being implemented inside the router. The new version v3.0.0 fixes that. Check the [docs about error handling](https://oas-tools.github.io/docs/features/error-handling) in the new version.
