### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by mlaass** [oas-tools/oas-tools#185]
Typescript definitions would be nice. I can look into it and do a pull request once I have something going.

**Comment by DJFarr** [comment]
Seconding this, definitions would be handy.

**Comment by GianKiMoon** [comment]
Any updates on this one, @jomoho?

**Comment by alesancor1** [comment]
I am planning a migration to TS for future releases. I will take your sugestion into account :)
I will open an issue about it soon.
