### ISSUE TITLE
npm audit returns error with v2.1.7

### ISSUE THREAD

**Issue by johnnygf** [oas-tools/oas-tools#188]
npm audit errors have been observed with oas-tools 2.1.7

Our Jenkins CI nodes generally run nodejs 10.15.3 (npm 6.4.1) or 10.16.3 (npm 6.9.0).

With npm 6.4.1 (locally or in Jenkins) we get the following error
```
npm ERR! code E400
npm ERR! 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits
```

With npm 6.9.0 (locally or in Jenkins)
```
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.
```

Workaround: use oas-tools 2.1.6

**Comment by johnnygf** [comment]
Verified with a minimal project
```
➜  test-oas-tools npm install --save oas-tools
...
+ oas-tools@2.1.7
added 530 packages from 427 contributors in 157.772s
➜  test-oas-tools npm -v   
6.11.3
➜  test-oas-tools nvm use lts/dubnium
Now using node v10.16.3 (npm v6.9.0)
➜  test-oas-tools npm audit --registry=https://registry.npmjs.com/
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.com/) does not support audit requests, or the audit endpoint is temporarily unavailable.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/n0357581/.npm/_logs/2019-10-11T11_24_32_125Z-debug.log
➜  test-oas-tools nvm use lts/carbon
Now using node v8.16.1 (npm v6.4.1)
➜  test-oas-tools npm audit --registry=https://registry.npmjs.com/
npm ERR! code E400
npm ERR! 400 Bad Request - POST https://registry.npmjs.com/-/npm/v1/security/audits

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/n0357581/.npm/_logs/2019-10-11T11_25_04_557Z-debug.log
➜  test-oas-tools cat package.json
{
  "name": "test-oas-tools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "oas-tools": "^2.1.7"
  }
}
```

**Comment by johnnygf** [comment]
➜  test-oas-tools npm install --save oas-tools
...
+ oas-tools@2.1.7
added 530 packages from 427 contributors in 157.772s
➜  test-oas-tools npm -v   
6.11.3
➜  test-oas-tools nvm use lts/dubnium
Now using node v10.16.3 (npm v6.9.0)
➜  test-oas-tools npm audit --registry=https://registry.npmjs.com/
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.com/) does not support audit requests, or the audit endpoint is temporarily unavailable.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-10-11T11_24_32_125Z-debug.log
➜  test-oas-tools nvm use lts/carbon
Now using node v8.16.1 (npm v6.4.1)
➜  test-oas-tools npm audit --registry=https://registry.npmjs.com/
npm ERR! code E400
npm ERR! 400 Bad Request - POST https://registry.npmjs.com/-/npm/v1/security/audits

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-10-11T11_25_04_557Z-debug.log
➜  test-oas-tools cat package.json
{
  "name": "test-oas-tools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "oas-tools": "^2.1.7"
  }
}

**Comment by johnnygf** [comment]
This might be weird proxy issues within my organisation, which we're trying to diagnose. Will update/close issue when I find out more.

**Comment by raffrearaUS** [comment]
Did you find out the issue? I cannot seem to reproduce this behaviour.
