### ISSUE TITLE
No Accept in Request

### ISSUE THREAD

**Issue by davegrix** [oas-tools/oas-tools#194]
v.2.1.7

How can I handle when a request does not include an Accept in its headers?

oas-router fails on 
`var validSchema = _.cloneDeep(responseCodeSection.content['application/json'].schema);`

with 
 Cannot read property 'schema' of undefined

My spec

```paths:
  /hello:
    post:
      x-router-controller: basictraining
      summary: return a TwiML
      description: returns a <Say> tag
      operationId: sayHello
      tags:
        - General
      responses:
        '200':
          description: OK
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/helloTwiML'


components:
  schemas:
    helloTwiML:
      type: object
      properties:
        Response:
          type: object
          properties:
           Say:
             type: string
```

**Comment by tuunit** [comment]
Hi @davegrix,
I recently had an issue with the way the validation of the accepted MIME types works as well and fixed it. Could you please retest with the latest release (2.1.8). It might fix your issue as well. If not let me know. I might have a simple change in mind that could resolve the issue in the implementation.

**Comment by alesancor1** [comment]
The response validation has been isolated to a new middleware in the [v3.0.0](https://oas-tools.github.io), the behaviour for the content-type validation has been fixed: when no content type is set in request it will assume `*/*`and will pass the validation.
