### ISSUE TITLE
Default parameter value not being set during validation

### ISSUE THREAD

**Issue by rolandfung** [oas-tools/oas-tools#228]
https://github.com/isa-group/oas-tools/blob/5239f93f1f1a616065fc892a41dfddc14b868415/src/middleware/oas-validator.js#L244

Default value is at parameter.schema.default, not parameter.default. This causes the default value to not be applied during validation (remains undefined) when an optional parameter is not specified.

**Comment by alesancor1** [comment]
This behaviour has been fixed in v3.0.0. Check the [documentation](https://oas-tools.github.io).
