### ISSUE TITLE
res.locals is null when setting { validator: false } on configuration.

### ISSUE THREAD

**Issue by reynanzeniarkgithub** [oas-tools/oas-tools#229]
I'm receiving an error "Cannot read property 'paths' of undefined"

Below is my configuration:

` 
  oasTools.configure({
    controllers: path.join(__dirname, './src/components'),
    customErrorHandling: true,
    validator: false,
  });
`

Checked the root cause, and it's probably here:

`oas-tools\src\middleware\oas-router.js`
`213: var oasDoc = res.locals.oasDoc;`
`214: var requestedSpecPath = res.locals.requestedSpecPath; //requested path version on the oasDoc file of the requested url`

Sorry this is my first time to submit an issue like this.

Thank you! Hope it helps.

**Comment by greuze** [comment]
Same bug as https://github.com/isa-group/oas-tools/issues/127
