### ISSUE TITLE
A mechanism to hide end points from Swagger UI.

### ISSUE THREAD

**Issue by sarang4488** [oas-tools/oas-tools#244]
A boolean like (x-hidden) which could be added to the endpoint definition such that it exists in the YAML file but is not visible on the swagger UI.

I was working on a use case where we need to hide some endpoints which are for internal use and could not find a way to achieve this using oas tools. Will love to have this feature

**Comment by sarang4488** [comment]
I apologise if this feature already exists. If so, can anyone guide me how can I achieve hiding of end points in the UI.

**Comment by alesancor1** [comment]
This feature is available in the latest version. Check out the [documentation](https://oas-tools.github.io/docs/features/swaggerUI)
