### ISSUE TITLE
Bug: Only 'required' parameters are validated

### ISSUE THREAD

**Issue by mjf-acqyrexchange** [oas-tools/oas-tools#250]
The validator seems to ignore errors in the query parameters if the parameter is not required, but is present in the url. For example, I don’t get an error sending this url:

http://localhost:8080/acQyreXchange/acQyr-sample/1.0.0/gamer/123?limit=-3&xyz=a

I would expect it to complain about ‘limit’ being out of range (-3 < 0), and ‘xyz’ being an unknown parameter. I get an error message about wrong data in the response (which I’m expecting), but nothing about the inputs.
```
[
	•	{
		o	message: "Wrong data in the response. ",
		o	error: 
			[
				{
					code: "INVALID_TYPE",
					params: 
					[
						"array",
						"object"
					],
					message: "Expected type array but found type object",
					path: "#/"
				}
			],
		o	content: 
			{
				message: "This is the mockup controller for getGamer"
			}
	•	}
]
```
The log shows:
2020-09-01T14:49:11.670Z info: Requested method-url pair: get - /acQyreXchange/acQyr-sample/1.0.0/gamer/123?limit=-3&xyz=a
2020-09-01T14:49:11.671Z debug: OASValidator  -res.locals.requestedSpecPath: /gamer/{gamerId}
2020-09-01T14:49:11.673Z info: Valid parameter on request
2020-09-01T14:49:11.675Z debug: Processing at checkResponse:

The api doc shows:
```
  '/gamer/{gamerId}':
    get:
      tags:
        - admins
      summary: 'given a gamerId, returns a gamer'
      operationId: getGamer
      description: Returns a gamer
      parameters:
        - in: path
          name: gamerId
          description: pass the gamerId for looking up the gamer
          required: true
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gamer'
        '400':
          description: bad input parameter
```

I’ve tried option:
strict: true (also tried false)
validator: true (also tried false)
customErrorHandling: true (also tried false)

I believe I have a fix (locally); I've tried it with some cases.

**Comment by rpkale** [comment]
I believe this is happening for header parameters also (not just query parameters)

**Comment by alesancor1** [comment]
This issue has been fixed in the last version. Check out the docs [here](https://oas-tools.github.io/docs/getting-started/overview)
