### ISSUE TITLE
Extraneous query parameters not flagged as errors

### ISSUE THREAD

**Issue by mjf-acqyrexchange** [oas-tools/oas-tools#251]
A url that contains a query parameter that is not defined in the API is not flagged as an error. This can be dangerous if a request has a misspelled, non-required parameter. The request thinks it's asking for something but in fact will be ignored by the server.

For example, I might have:

```
https://api.me.me/pets?typ=calico
```
and the query parameter should be 'type'. If the 'type' parameter is not required, no errors are thrown. The caller thinks the 'type' parameter was sent correctly, but it wasn't, and the server ignores the parameter (as it's not a defined parameter); no error response is sent.

I can see making this sort of check optional, but I would think that's ignoring the whole point of having an API spec and checking against it.

I have a fix locally.

**Comment by alesancor1** [comment]
A new release that solves this issue has been published (`v3.0.2`). Please run `npm update @oas-tools/core` to update OAS Tools core library. See the [Release Notes](https://github.com/oas-tools/oas-tools/pull/348).
