### ISSUE TITLE
fixNullable() is recursively updating types

### ISSUE THREAD

**Issue by stephenbeauchamp** [oas-tools/oas-tools#253]
There is a helper function:
  src/lib/utils.js > fixNullable(schema)

It scans for nullable properties and converts their type from 
  type: 'xyz' 
to 
  type: [ 'xyz', "null" ]

Very helpful! Thanks for fixing that! But there is an issue.

If this is run over the schema more than once, then subsequent runs you get:
  type: [ ['xyz', "null"], "null" ]
  type: [ [ ['xyz', "null"], "null" ], "null"]
  type: [ [ [ ['xyz', "null"], "null" ], "null"], "null"]

I suggest we test that the conversion hasn't already been done before running the fix up.

**Comment by stephenbeauchamp** [comment]
Sorry, I logged an issue so I would have a sensible branch name for the PR .... I see the PR creates it's own issue, so this is a duplicate of #254 - and has the wrong branch name!

**Comment by Hippo0o** [comment]
When can we expect a new release? I'm kinda needing this bug to be fixed ASAP.

**Comment by lupus92** [comment]
I also need it ASAP... Would be nice if the next release can be done soon!

**Comment by alesancor1** [comment]
`fixNullable()` is no longer used in the new version of OAS Tools. As of `v3.0.2` nullable values are parsed correctly.
