### ISSUE TITLE
Express as a development dependency

### ISSUE THREAD

**Issue by kerrerain** [oas-tools/oas-tools#256]
Hello,

I was wondering why express was declared in the devDependencies section instead of the dependencies section of package.json, althought it is required at runtime (at line 24 of index.js).

This is a detail that is detected by the version 2 of Yarn, that was released recently. For example, given this package.json:

```json
{
  "name": "some-module",
  "version": "1.0.0",
  "main": "index.js",
  "author": "kerrerain",
  "license": "MIT",
  "dependencies": {
    "express": "^4.17.1",
    "oas-tools": "^2.1.7"
  }
}
```

Running `yarn install` and `yarn node .` at the root of the module raises an error:

```
2020-09-24T07:24:18.792Z error: uncaughtException: oas-tools tried to access express, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: express (via "express")
Required by: oas-tools@npm:2.1.8 (via C:\Users\h.bonjour\home\projects\makesense\workspace\targets\juliena\.yarn\cache\oas-tools-npm-2.1.8-fa42a3c17e-3f457b30be.zip\node_modules\oas-tools\src\)
```

There are workarounds to handle this error with Yarn, so that's not really an issue. I was mostly curious.

**Comment by acotty** [comment]
Looks like a bug. I use depcheck (https://www.npmjs.com/package/depcheck) to find these and other issues with packages.

**Comment by alesancor1** [comment]
Hello, dependencies like express and mongoose has been moved to devDependencies or removed from project since they are used for testing purposes.
