### ISSUE TITLE
response validation to validate parsed response not original source object

### ISSUE THREAD

**Issue by stephenbeauchamp** [oas-tools/oas-tools#257]
This is to go with PR: https://github.com/isa-group/oas-tools/pull/255

Response validation to validate parsed response rather than the response's original source object.

I am having issues that my controller returns an object with date fields, which the schema says should be strings (as is the case in a JSON representation of the object). This is causing the validation to throw errors even though the payload is valid.

This change parses the JSON response that has been created back into an object for validation, rather than validating the original object that was returned from the controller.

We start with > ControllerOutput [object]
We transform it > Response = JSON.stringify(ControllerOutput) [string]
This change proposes > ValidatedObject = JSON.parse(Response) [object]

Validation of the ControllerOutput fails. [current state]
Validation of the ValidatedObject passes. [new state]

I have no idea if this is on the right track or if I'm just doing something very wrong with my controllers returning date fields? But this fixed the issue for me so I submit it for your consideration.

**Comment by alesancor1** [comment]
This behaviour has been fixed in the v3.0. The validator now validates the parsed response. Check out the [documentation](https://oas-tools.github.io/docs/features/validation).
