### ISSUE TITLE
using $ref on Remote Reference files returns error "Not Found"

### ISSUE THREAD

**Issue by sageguy09** [oas-tools/oas-tools#260]
We are attempting to move some of our API definitions to their own yaml/json file and use [$ref to point to the other definition file](https://swagger.io/docs/specification/using-ref/). However, after starting server, we see a resolver error on swagger-ui with the following: _"Could not resolve reference because of: Not Found"_ . It does not appear that OAS-Tools is handling the remote references appropriately. 

For example, if we were to extract [your test project's first endpoint body schema definition](https://github.com/isa-group/oas-tools/blob/69834f2a00c1ef5fa6a5ff93f9a693b3f3d7c613/tests/testServer/api/oai-spec.yaml#L24-L37) to a file called "pet.json" and update the oas-spec.yaml to the following:

```yaml
.......
paths:
  /multipartFormdata:
    post:
      summary: testing a multipart form with upload file and regular parameters
      operationId: createPetsViaMultipartFormdata
      x-router-controller: "petsController"
      tags:
        - pets
      requestBody:
        required: true
        description: Pet to add to the store via an uploaded file and regular parameters
        x-name: petViaForm
        content:
          multipart/form-data:
            schema:
             $ref: 'pets.json'
      responses:
        '201':
                 ........
```

and pets.json would look like :

```json
{
  "type": "object",
  "required": [
     "file",
     "id",
     "name"
  ],
  "properties": {
     "file": {
        "type": "string",
        "format": "binary",
        "description": "a binary file uploaded via openAPI spec"
     },
     "id": {
        "type": "string"
     },
     "name": {
        "type": "string"
     }
  }
}
```
NOTE: we tested with setting the remote reference to "./pets.json" as well. 

Let me know if I can provide any more information to assist in testing/resolving this issue. 

Cheers

**Comment by plaurent** [comment]
@sageguy09 Thanks for filing this issue.  I ran into this same issue a few days ago -- specifically trying to load remote references from a URL -- and have just completed what I believe is a working implementation.

**Comment by plaurent** [comment]
@sageguy09 Just letting you know that this branch/PR now also supports loading schemata from local files  (using ./ ../ or file://).

**Comment by sageguy09** [comment]
Perfect. This is exactly what we need. Looking forward to implementing once this PR is merged. Thank you again!

**Comment by alesancor1** [comment]
Hello, Thanks to the json-schema-ref-parser library this feature is available in the new version. Check the [documentation](https://oas-tools.github.io)
