### ISSUE TITLE
For Basic auth, verify function isn't passed the Authorization string

### ISSUE THREAD

**Issue by mjf-acqyrexchange** [oas-tools/oas-tools#280]
I define Basic auth. My verify function gets passed good arguments except for the third, which is undefined. I have to access the Authorization header/string from the request object. The documentation leads me to believe I would get that string as the third arg:
> simply create a function that takes the express req object, the security scheme, the value that will be validated, and a callback as inputs.

Here's the code that works:
```
module.exports.verifyLogin = function verifyLogin( req, secDef, notUsed, next ) {
  const auth = req.headers.authorization;
  const bearerRegex = /^Basic\s/;

  if ( bearerRegex.test( auth ) ) {
    let newAuth = auth.replace( bearerRegex, '' );
    newAuth = Buffer.from( newAuth, 'base64' ).toString( 'ascii' );
    console.log( `verifyLogin got decoded Authorization: ${ newAuth }` );
    next();
  }
};
```
Argument `secDef` is, indeed, 'Basic'. The `notUsed` argument is `undefined` when the module gets called.

My options file contains:
```
  oasSecurity: true,
  securityFile: {
    basicAuth: loginService.verifyLogin
  }
```

**Comment by alesancor1** [comment]
Hello, the new version 3.0 automatically reads the security schemes and passes the token to your handler. You can check out the [documentation](https://oas-tools.github.io/docs/features/security) for more info.
