### ISSUE TITLE
Update version of Swagger UI to latest 3.47.0 (2021-04-15)

### ISSUE THREAD

**Issue by pandominox** [oas-tools/oas-tools#284]
Update version of Swagger UI from commit 72aaf92, 2018-08-28 (maybe v3.18.2) to latest, stable version v3.47.0 (2021-04-15).
Source link: [github](https://github.com/swagger-api/swagger-ui/archive/refs/tags/v3.47.0.zip)
 
Copy of files from the /dist folder:
- favicon-16x16.png
- favicon-32x32.png
- index.html
- oauth2-redirect.html
- swagger-ui.css
- swagger-ui-bundle.js
- swagger-ui-standalone-preset.js

**Comment by alesancor1** [comment]
Hello, Swagger UI has been updated to [v4.5.2](https://github.com/swagger-api/swagger-ui/releases/tag/v4.5.2) released on February 2022.
