### ISSUE TITLE
Parameter type: string, format: date throws: Expected type string but found type object.

### ISSUE THREAD

**Issue by Hippo0o** [oas-tools/oas-tools#289]
Validation validates type: string in: https://github.com/isa-group/oas-tools/blob/d779cea2213a3cc7b9282bdd7c86f70730b0268e/src/middleware/oas-validator.js#L173
but gets Date object created in: 
https://github.com/isa-group/oas-tools/blob/d779cea2213a3cc7b9282bdd7c86f70730b0268e/src/middleware/oas-validator.js#L379

**Comment by alesancor1** [comment]
Hello, since the release of v3.0.0, this problem has been solved and OAS Tools now support parameter validation of any type. Check the docs [here](https://oas-tools.github.io/docs/getting-started/overview).
