### ISSUE TITLE
Critical vulnerability with json-schema-deref > mpath

### ISSUE THREAD

**Issue by franBlopez** [oas-tools/oas-tools#297]
currently the mpath@~0.5.0 package has a critical vulnerability, they plan to update it?

│| Critical      │| Type confusion                                               │|
│ Package       │ mpath                                                        │
│ Patched in    │ >=0.8.4                                                      │
│ Dependency of │ oas-tools                                                    │
│ Path          │ oas-tools > json-schema-deref > mpath                        │
│ More info     │ https://npmjs.com/advisories/1785   |

**Comment by olvresc** [comment]
Hi @raffrearaUS, any update on this? Thank you.

**Comment by alesancor1** [comment]
Hi, this vulnerability has been patched for the released 2.2.0 version. Check #304 .
