### ISSUE TITLE
Upgrade to 2.2.0 fails with ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by antoine-wbr** [oas-tools/oas-tools#306]
When I use version 2.2.0 and try to start my app, I get this error:
```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/node_modules/oas-tools/lib/index.mjs' imported from /app/index.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:398:11)
    at moduleResolve (node:internal/modules/esm/resolve:957:10)
    at defaultResolve (node:internal/modules/esm/resolve:1166:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:536:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:250:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

When I rollback to 2.1.8 everything is back to normal. Not sure what is in 2.2.0 so it's difficult for me to figure out if there is something to change in my code.

**Comment by alesancor1** [comment]
Hello, this was a bug with the babel plugin not transpiling the code to commonJS and ESM. I deprecated the package and released 2.2.1 version solving that issue. Run `npm update` on your project and the problem should be gone.

**Comment by raoulkent** [comment]
I'm having the same problem as @antoine-wbr running 2.2.1.
Running `yarn upgrade` does not help. And I have verified that it's 2.2.1.

**Comment by alesancor1** [comment]
Looking at the error trace, it seems you are running oas-tools using ESM (`"type":"module"` in your package.json) and the /utils.js file couldn't be found. I think it may be due to ESM not being able to resolve directory imports, try using the `--experimental-specifier-resolution=node`  when starting your server.

Anyway, I am currently working in a new version fully compatible with ESM, without Babel, since it looks like ES Modules are the way to go for NodeJS.

**Comment by raoulkent** [comment]
> It seems you are running oas-tools using ESM (`"type":"module"` in your package.json)
This is accurate for me as well. I can give it a try with the `--experimental-specifier-resolution=node` and see if that solves it. But if you're working on making it ESM by default then that's awesome :)
