### ISSUE TITLE
Is their any way to ignore response validation?

### ISSUE THREAD

**Issue by jagdish-176** [oas-tools/oas-tools#327]
I don't want to validate response data, is there any option to ignore response validation.

On Swagger tools I had option
```
_swagger_validate:
      name: swagger_validator
      validateResponse: false

```

**Comment by sscots** [comment]
Any update on this?

**Comment by alesancor1** [comment]
OAS Tools v3 is already out, you can disable response validation through configuration. Check the [docs](https://oas-tools.github.io/docs/fundamentals/config)
