### ISSUE TITLE
[BUG] server property in swagger file no longer working

### ISSUE THREAD

**Issue by jagdish-176** [oas-tools/oas-tools#341]
## **Describe the bug**
V3 no longer support base paths.
servers:
   - url: /v1

## **To Reproduce**
1. Create new project with `npx @oas-tools/cli init`
2. In swagger.yaml file add below
       servers:
          - url: /v1
3. I should be able to access **http://localhost:8080/v1/test**
4. But instead I get error 404
5. If I try http://localhost:8080/test it works

I thought it's easier to migrate from V2 to V3, but it's hard.
1. Previously I used x-swagger-router-controller, now its x-router-controller
2. I need to specify .js extension in x-router-controller: admin.js otherwise it takes admin.d.ts
3. I stopped migrating for now.

**Comment by alesancor1** [comment]
Hello, thanks for your report! I see you've had some problems migrating to v3. 

First, the `x-swagger-router-controller` being replaced by `x-router-controller` is not documented in the migration guide, so I will add it. Anyway, since swagger-tools was widely used by the current OAS Tools users, I'm planning to add a compatibility middleware for swagger-tools in order to bring support to what was included there. 

I will also take a look to the `.js` extension being a default in case no other extension is set in `x-router-controller`.

With regard to the bug of this issue, I know that the `servers` are not currently supported. I'm preparing a new version that brings full support to them.

**Comment by iofirag** [comment]
took me alot time to understand thats **servers** property not working well ..
i also stop using this version for now.
:-/

**Comment by alesancor1** [comment]
I'm currently working on a fix for the next version to support OpenAPI `servers` property. However, there are some other bugs I need to fix so it may take some time, but I will release it asap :-)

**Comment by alesancor1** [comment]
A new release that solves this issue has been published (`v3.0.2`). Please run `npm update @oas-tools/core` to update OAS Tools core library. See the [Release Notes](https://github.com/oas-tools/oas-tools/pull/348).

**Comment by iofirag** [comment]
still not works after update to v3.0.2
the behavior still the same as wrote in the description of the issue

**Comment by alesancor1** [comment]
I couldn't reproduce the error with v3.0.2, it works fine for me, here is the OpenAPI file I used:
```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Data Service
servers:
- url: /api/v1
paths:
  /test-endpoint:
    get:
      x-router-controller: testController
      operationId: getRequest
      responses:
        200:
          description: test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/placeholderModel'
components:
  schemas:
    placeholderModel:
      type: object
      additionalProperties: true
```

I ran `npx @oas-tools/cli init` and generated a server using this spec. Once generated I ran `npm start` into the server directory, made a GET request to `/api/v1/test-endpoint` and got  `{"message":"This is the mockup controller for getRequest"}` just as expected.

NOTE: This new version also supports the `servers` property at the path and operation levels.

**Comment by iofirag** [comment]
tried your .yaml exactly, 
run manually install by `yarn add @oas-tools/core` and check in package json that version 3.0.2 installed.

and create new controller in controllers folder called 'testController'
with function called 'getRequest'
and init oasTools with configuration:

```
## oasConfig:
const oasConfig = {
        "oasFile": "./api/oas.yaml",
        "middleware": {
            "validator": {
                "strict": true
            },
            "router": {
                "controllers": "./controllers"
            }
        }
 }
const express = require('express');
const app = express();
await oasTools.initialize(app, oasConfig);
```

```
## controllers/testController.js
module.exports.getRequest = (req, res) => {
    res.end(JSON.stringify({ aa: 33 }));
};
```

maybe when you ran ` npx @oas-tools/cli init` it working differently than just `yarn add @oas-tools/core` ?

**Comment by alesancor1** [comment]
Still not able to reproduce this. I use your exact controller, with the same OpenAPI spec file and this index.js:

```js
const oasTools = require('@oas-tools/core');
const http = require('http');
const express = require('express');
const app = express();

const oasConfig = {
    "oasFile": "./api/oas.yaml",
    "middleware": {
        "validator": {
            "strict": true
        },
        "router": {
            "controllers": "./controllers"
        }
    }
}

oasTools.initialize(app, oasConfig).then(() => http.createServer(app).listen(8080));
```

GET request to `http://localhost:8080/api/v1/test-endpoint` returns `{"aa":33}` just as expected.

I leave you here the server in .zip format:  [test-server.zip](https://github.com/oas-tools/oas-tools/files/9673866/test-server.zip)

**Comment by iofirag** [comment]
Good news, it's work.
Deleting the yarn.lock / package-lock.json file and install - fixed my problem :)
(your zip file help me lot understand this fix.)

> Still not able to reproduce this. I use your exact controller, with the same OpenAPI spec file and this index.js:
> 
> ```js
> const oasTools = require('@oas-tools/core');
> const http = require('http');
> const express = require('express');
> const app = express();
> 
> const oasConfig = {
>     "oasFile": "./api/oas.yaml",
>     "middleware": {
>         "validator": {
>             "strict": true
>         },
>         "router": {
>             "controllers": "./controllers"
>         }
>     }
> }
> 
> oasTools.initialize(app, oasConfig).then(() => http.createServer(app).listen(8080));
> ```
> 
> GET request to `http://localhost:8080/api/v1/test-endpoint` returns `{"aa":33}` just as expected.
> 
> I leave you here the server in .zip format: [test-server.zip](https://github.com/oas-tools/oas-tools/files/9673866/test-server.zip)

**Comment by iofirag** [comment]
Good news, it's work.
Deleting the yarn.lock / package-lock.json file and install - fixed my problem :)
(your zip file help me lot understand this fix.)
