### ISSUE TITLE
How to use http query params with oas tools?

### ISSUE THREAD

**Issue by Joshua-Tu** [oas-tools/oas-tools#347]
Here goes my open API 3.0 specs
```
"/templates": {
      "get": {
        "x-swagger-router-controller": "templates",
        "x-swagger-router-handle-subpaths": false,
        "operationId": "getTemplates",
        "tags": ["Templates"],
        "description": "API to get list of templates",
        "parameters": [
          {
            "name": "filterUseCases",
            "in": "query",
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "onboarding",
                  "offboarding"       
                ]
              }
            }
          }
        ]
}
```
I used the following way to send the query params to send the array,
<img width="1963" alt="image" src="https://user-images.githubusercontent.com/47619573/192245086-50c8e940-b592-4058-8a5b-358fe62849ff.png">
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/47619573/192245354-5478b947-5997-4c81-a543-5c0930781e46.png">
<img width="1899" alt="image" src="https://user-images.githubusercontent.com/47619573/192245411-51ea51c9-46f6-48f8-8ebd-690b6f9b2107.png">

I always got "array expected but found string" or "convertArrayValue failed" or "cannot read map of undefined" error
Could anyone help with this?

Cheers.

**Comment by alesancor1** [comment]
Hello, which version of OAS Tools are you using? I could not reproduce your situation, it works fine for me. I'm using OAS Tools v3.0.1 since full support for parameter serialization was implemented in `v3.0.0`.

I copied your parameters' spec into a development server's endpoint and sent a request just as you did:

```GET http://localhost:8080/api/v1/test-dev-server?filterUseCases=onboarding&filterUseCases=offboarding```

```yaml
# Spec
/test-dev-server:
    get:
      x-router-controller: devServerController
      operationId: getRequest
      "parameters": [
          {
            "name": "filterUseCases",
            "in": "query",
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "onboarding",
                  "offboarding"       
                ]
              }
            }
          }
        ]
      responses:
        200:
          description: test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/placeholderModel'
```

Then I printed to console `res.locals.oas` object and got:
```js
{
  params: { filterUseCases: [ 'onboarding', 'offboarding' ] },
  body: {}
}
```

Also, please consider using [OAS Tools' discussions](https://github.com/orgs/oas-tools/discussions) for this kind of issues.

**Comment by Joshua-Tu** [comment]
Thanks, @alesancor1 , I was using version 2.2.2 when I posted this question

**Comment by Joshua-Tu** [comment]
@alesancor1 just migrate this question to oas-tools discussion
