### ISSUE TITLE
Align js-yaml version with @oas-tools/commons

### ISSUE THREAD

**Issue by pebo** [oas-tools/oas-tools#364]
## **Describe the bug**
`@oas-tools/core` uses` js-yaml` v3.x and `@oas-tools/commons` uses `js-yaml` v4.x. This results in duplicate versions of the library being installed.

`@oas-tools/core` should be upgrade to v4.x

## **To Reproduce**
`npm list --omit=dev --depth 2 | grep js-yaml`

## **Expected behavior**
The same major version should be used to avoid duplicates.

## **Screenshots**
n/a

## **Desktop (please complete the following information):**
n/a

## **Smartphone (please complete the following information):**
n/a

**Comment by alesancor1** [comment]
Great, thanks for creating the PR, too. I move this to done, it will be closed when release 3.1.0 is published :)
