### ISSUE TITLE
oneOf keyword in swagger.yml not working

### ISSUE THREAD

**Issue by itsonlyashish** [oas-tools/oas-tools#80]
Hi,

I am trying use the oneOf keyword in the OpenApi 3.0 specs. I am using the example on Swagger site (https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/). My swagger.yml has the following in it:
```yaml 
 /testschema:
    post:
      description: Create app data storage
      operationId: testSchema
      security:
        []
      x-security-scopes:
        - Admin
      x-swagger-router-controller: public        
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
        description: The app data schema
        required: true
      responses:
        "200":
          description: The app data schema was already initialized

components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer  
```

While trying to a Postman call with the following `body,` it is not recognizing and giving the below error. If I change the oneOf to anyOf, then everything passes (which also does not seem to be the correct behavior)
```JSON
{
  "bark": true,
  "breed": "Dingo"
}
```
Error received:
```JSON
[
    {
        "message": "Wrong data in the body of the request. ",
        "error": [
            {
                "code": "ONE_OF_MULTIPLE",
                "params": [],
                "message": "Data is valid against more than one schema from 'oneOf'",
                "path": "#/"
            }
        ],
        "content": {
            "bark": "true",
            "breed": "Dingo"
        }
    }
]
```

**Comment by stukker01** [comment]
After a few days of debugging I found out, that this is not a bug. It's the expected behaviour, however the description on Swagger's site is misleading and the examples are incorrect.
See my issue for more details: https://github.com/swagger-api/swagger.io/issues/253

I also tested the above example with required fields and disallowed additional properties and the validation worked as expected.
