### ISSUE TITLE
 [Bug] Get with query parameter :  allowReserved=true  doesn't work

### ISSUE THREAD

**Issue by engiwip** [oas-tools/oas-tools#89]
Hi all ,  following open api 3.0 spec as below
https://swagger.io/docs/specification/serialization/

- in:    query
          name: options
          style: form
          explode :false
          allowReserved :true
          schema:
            type: string .
          
result :
debug info

Requested method-url pair: get - /PostlabAI/PostlabAI/1.0.0/run/container/1/command/1?options=0%3D-i%257B%252Fapp%252Finput%252Ffile.txt%257D

should be : options=-i{/app/input/file.txt}
with reserved word like :  ' { } /'  allowed... but the uri is malformed when I parse that.

 Additionally, the allowReserved keyword specifies whether the reserved characters :/?#[]@!$&'()*+,;=

**Comment by raffrearaUS** [comment]
Even though the URL appears encoded in the log, I seem to be able to correctly retrieve the special characters in the controller. Do you suggest that these characters should be correctly logged, or are you refering to something else?

**Comment by engiwip** [comment]
I have to decode/normilze in UTF8 manually when I send a special character. like '#' for example.
I need to write a sugar function in javascript ( server side) as below 

export const decodeUTF8 = function (chain: string): string {
    return decodeURIComponent(chain) ;
} ;

If I don' t   : I have an error when my client is a php-client
